package cr.ac.una.prograiv.proyecto.Domain;
// Generated 07/11/2017 02:19:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellidos;
     private String correo;
     private String password;
     private Date fechaN;
     private String direccion;
     private String telefono;
     private String tipoUsuario;
     private Integer vehiculoactual;
     private Integer choferactual;
     private Date ultimaMod;
     private Integer ultModUs;

    public Usuario() {
    }

	
    public Usuario(int id, String nombre, String apellidos, String correo, String password, Date fechaN, String direccion, String telefono, String tipoUsuario) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.correo = correo;
        this.password = password;
        this.fechaN = fechaN;
        this.direccion = direccion;
        this.telefono = telefono;
        this.tipoUsuario = tipoUsuario;
    }

    public Usuario(int id, String nombre, String apellidos, String correo, String password, Date fechaN, String direccion, String telefono, String tipoUsuario, Integer vehiculoactual, Integer choferactual, Date ultimaMod, Integer ultModUs) {
        this.id = id;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.correo = correo;
        this.password = password;
        this.fechaN = fechaN;
        this.direccion = direccion;
        this.telefono = telefono;
        this.tipoUsuario = tipoUsuario;
        this.vehiculoactual = vehiculoactual;
        this.choferactual = choferactual;
        this.ultimaMod = ultimaMod;
        this.ultModUs = ultModUs;
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaN() {
        return this.fechaN;
    }
    
    public void setFechaN(Date fechaN) {
        this.fechaN = fechaN;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Integer getVehiculoactual() {
        return this.vehiculoactual;
    }
    
    public void setVehiculoactual(Integer vehiculoactual) {
        this.vehiculoactual = vehiculoactual;
    }
    public Integer getChoferactual() {
        return this.choferactual;
    }
    
    public void setChoferactual(Integer choferactual) {
        this.choferactual = choferactual;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Integer getUltModUs() {
        return this.ultModUs;
    }
    
    public void setUltModUs(Integer ultModUs) {
        this.ultModUs = ultModUs;
    }
    




}


