package cr.ac.una.prograiv.proyecto.Domain;
// Generated 07/11/2017 02:19:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private Conductor conductor;
     private String modelo;
     private int ahno;
     private String color;
     private int puntuacion;
     private String estado;
     private String ubicacion;
     private String marca;
     private int capPasaj;
     private Integer uusarioActual;
     private Date ultimaMod;
     private Integer ultModUs;
    

    public Vehiculo() {
    }

	
    public Vehiculo(String placa, Conductor conductor, String modelo, int ahno, String color, int puntuacion, String estado, String ubicacion, String marca, int capPasaj) {
        this.placa = placa;
        this.conductor = conductor;
        this.modelo = modelo;
        this.ahno = ahno;
        this.color = color;
        this.puntuacion = puntuacion;
        this.estado = estado;
        this.ubicacion = ubicacion;
        this.marca = marca;
        this.capPasaj = capPasaj;
    }

    public Vehiculo(String placa, Conductor conductor, String modelo, int ahno, String color, int puntuacion, String estado, String ubicacion, String marca, int capPasaj, Integer uusarioActual, Date ultimaMod, Integer ultModUs) {
        this.placa = placa;
        this.conductor = conductor;
        this.modelo = modelo;
        this.ahno = ahno;
        this.color = color;
        this.puntuacion = puntuacion;
        this.estado = estado;
        this.ubicacion = ubicacion;
        this.marca = marca;
        this.capPasaj = capPasaj;
        this.uusarioActual = uusarioActual;
        this.ultimaMod = ultimaMod;
        this.ultModUs = ultModUs;
    }
   
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public int getAhno() {
        return this.ahno;
    }
    
    public void setAhno(int ahno) {
        this.ahno = ahno;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getCapPasaj() {
        return this.capPasaj;
    }
    
    public void setCapPasaj(int capPasaj) {
        this.capPasaj = capPasaj;
    }
    public Integer getUusarioActual() {
        return this.uusarioActual;
    }
    
    public void setUusarioActual(Integer uusarioActual) {
        this.uusarioActual = uusarioActual;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Integer getUltModUs() {
        return this.ultModUs;
    }
    
    public void setUltModUs(Integer ultModUs) {
        this.ultModUs = ultModUs;
    }
    




}


