package cr.ac.una.prograiv.proyecto.Domain;
// Generated 02/11/2017 02:42:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String placa;
     private Conductor conductor;
     private String modelo;
     private int ahno;
     private String color;
     private int puntuacion;
     private String estado;
     private String ubicacion;
     private Integer uusarioActual;
     private Integer choferactual;
     private Date ultimaMod;
     private Integer ultModUs;
     private Set<Viaje> viajes = new HashSet<Viaje>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String placa, Conductor conductor, String modelo, int ahno, String color, int puntuacion, String estado, String ubicacion) {
        this.placa = placa;
        this.conductor = conductor;
        this.modelo = modelo;
        this.ahno = ahno;
        this.color = color;
        this.puntuacion = puntuacion;
        this.estado = estado;
        this.ubicacion = ubicacion;
    }
    public Vehiculo(String placa, Conductor conductor, String modelo, int ahno, String color, int puntuacion, String estado, String ubicacion, Integer uusarioActual, Integer choferactual, Date ultimaMod, Integer ultModUs, Set<Viaje> viajes) {
       this.placa = placa;
       this.conductor = conductor;
       this.modelo = modelo;
       this.ahno = ahno;
       this.color = color;
       this.puntuacion = puntuacion;
       this.estado = estado;
       this.ubicacion = ubicacion;
       this.uusarioActual = uusarioActual;
       this.choferactual = choferactual;
       this.ultimaMod = ultimaMod;
       this.ultModUs = ultModUs;
       this.viajes = viajes;
    }
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public int getAhno() {
        return this.ahno;
    }
    
    public void setAhno(int ahno) {
        this.ahno = ahno;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Integer getUusarioActual() {
        return this.uusarioActual;
    }
    
    public void setUusarioActual(Integer uusarioActual) {
        this.uusarioActual = uusarioActual;
    }
    public Integer getChoferactual() {
        return this.choferactual;
    }
    
    public void setChoferactual(Integer choferactual) {
        this.choferactual = choferactual;
    }
    public Date getUltimaMod() {
        return this.ultimaMod;
    }
    
    public void setUltimaMod(Date ultimaMod) {
        this.ultimaMod = ultimaMod;
    }
    public Integer getUltModUs() {
        return this.ultModUs;
    }
    
    public void setUltModUs(Integer ultModUs) {
        this.ultModUs = ultModUs;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }




}


