package cr.ac.una.prograiv.proyecto.Domain;
// Generated 21/11/2017 08:10:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private int id;
     private Conductor conductor;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private Date fecha;
     private Date horaIn;
     private Date horaFn;
     private double precioTotal;
     private String puntoI;
     private String puntoFinal;
     private double distancia;

    public Viaje() {
    }

    public Viaje(int id, Conductor conductor, Usuario usuario, Vehiculo vehiculo, Date fecha, Date horaIn, Date horaFn, double precioTotal, String puntoI, String puntoFinal, double distancia) {
        this.id = id;
        this.conductor = conductor;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.fecha = fecha;
        this.horaIn = horaIn;
        this.horaFn = horaFn;
        this.precioTotal = precioTotal;
        this.puntoI = puntoI;
        this.puntoFinal = puntoFinal;
        this.distancia = distancia;
    }

    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraIn() {
        return this.horaIn;
    }
    
    public void setHoraIn(Date horaIn) {
        this.horaIn = horaIn;
    }
    public Date getHoraFn() {
        return this.horaFn;
    }
    
    public void setHoraFn(Date horaFn) {
        this.horaFn = horaFn;
    }
    public double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(double precioTotal) {
        this.precioTotal = precioTotal;
    }
    public String getPuntoI() {
        return this.puntoI;
    }
    
    public void setPuntoI(String puntoI) {
        this.puntoI = puntoI;
    }
    public String getPuntoFinal() {
        return this.puntoFinal;
    }
    
    public void setPuntoFinal(String puntoFinal) {
        this.puntoFinal = puntoFinal;
    }
    public double getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(double distancia) {
        this.distancia = distancia;
    }




}


