package cr.ac.una.prograiv.proyecto.Domain;
// Generated 07/11/2017 02:19:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private int id;
     private Conductor conductor;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private Date fecha;
     private Date horaIn;
     private Date horaFn;
     private double precioTotal;

    public Viaje() {
    }

	
    public Viaje(int id, Conductor conductor, Usuario usuario, Vehiculo vehiculo, Date fecha, Date horaIn, Date horaFn, double precioTotal) {
        this.id = id;
        this.conductor = conductor;
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.fecha = fecha;
        this.horaIn = horaIn;
        this.horaFn = horaFn;
        this.precioTotal = precioTotal;
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraIn() {
        return this.horaIn;
    }
    
    public void setHoraIn(Date horaIn) {
        this.horaIn = horaIn;
    }
    public Date getHoraFn() {
        return this.horaFn;
    }
    
    public void setHoraFn(Date horaFn) {
        this.horaFn = horaFn;
    }
    public double getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(double precioTotal) {
        this.precioTotal = precioTotal;
    }
   
}


